# Generated by Django 2.1.2 on 2018-11-06 20:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('type', models.CharField(choices=[('SOURCE', 'Source'), ('FOUNTAIN', 'Fontaine'), ('KIOSK', 'Kiosque'), ('INDIVIDUAL', 'Prise individuelle'), ('PIPE', 'Tuyau')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('OK', 'En service'), ('REPAIR', 'En réparation'), ('URGENT', 'Hors service (Urgent)'), ('KO', 'Hors service')], max_length=20, verbose_name='État')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='Longitude')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Multi-polygone')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('superzone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subzones', to='water_network.Zone', verbose_name='Superzone')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='water_network.Zone', verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='element',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='water_network.Location', verbose_name='Localité'),
        ),
    ]
