# Generated by Django 2.1.2 on 2018-11-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Localisation'),
        ),
    ]
