# Generated by Django 2.1.2 on 2018-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_auto_20181121_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='consumer',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Adresse'),
        ),
    ]
