# Generated by Django 2.1.2 on 2018-11-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('water_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=20, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], max_length=1, null=True, verbose_name='Genre')),
                ('phoneNumber', models.CharField(max_length=10, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Adresse email')),
                ('identifiant', models.CharField(max_length=20, verbose_name='Identifiant')),
                ('password', models.CharField(max_length=30, verbose_name='Mot de passe')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_network.Location', verbose_name='Localité')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
